version: '3.8'

services:
  php-fpm72:
    build:
      context: ./php/fpm
      args:
        - _PHP_VERSION=7.2
    environment:
      - TZ=Asia/Taipei
  php-fpm56:
    build:
      context: ./php/fpm
      args:
        - _PHP_VERSION=5.6
    environment:
      - TZ=Asia/Taipei
