name: CI

on:
  push:
    branches: '**'
  schedule:
    - cron: 0 0 * * 6

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ["7.2", "7.4"]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images:
            bestlong/php-test-base
          flavor: |
            prefix=${{ matrix.php_version }}-
          tags: |
            type=raw,value=latest
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        if: ${{ (github.repository == 'bestlong/php-test-base') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            _PHP_VERSION=${{ matrix.php_version }}
          context: php
          platforms: linux/amd64,linux/arm64
          push: ${{ (github.repository == 'bestlong/php-test-base') }}
          tags: ${{ steps.meta.outputs.tags }}
